<?php

namespace Tests\Application\Admin\Coaching\Controllers;

use Src\Application\Admin\Coaching\Controllers\CoachingController;
use Src\Domain\Performance\Models\Performance;
use Src\Domain\User\Enums\Roles;
use Src\Domain\User\Models\User;
use Tests\TestCase;

class CoachingControllerTest extends TestCase
{
    private User $user;

    protected function setUp(): void
    {
        parent::setUp();
        $this->user = User::factory()->withRole(Roles::ADMIN)->create();
        $this->actingAs($this->user);
    }

    /** @test */
    public function store(): void
    {
        $user_1 = User::factory()->create([
            'company_id' => $this->user->company_id,
            'email' => 'ignacio.irigoitia@gmail.com',
        ]);
        $user_2 = User::factory()->create(['company_id' => $this->user->company_id]);
        $coaching_data = [
            'subject' => 'Este es el asunto',
            'year' => 2023,
            'week' => 20,
            'category' => 'Fico Store',
            'content' => '<b>Este</b> es el contenido',
            'users' => [$user_1->id, $user_2->id],
            'type' => 'coach',
        ];

        $this->post(action([CoachingController::class, 'store']), $coaching_data)->assertOk();
        $this->assertDatabaseHas('coachings', [
            'subject' => 'Este es el asunto',
            'year' => 2023,
            'week' => 20,
            'category' => 'Fico Store',
            'content' => '<b>Este</b> es el contenido',
            'user_id' => $user_1->id,
            'type' => 'coach',
        ]);
        $this->assertDatabaseHas('coachings', [
            'subject' => 'Este es el asunto',
            'year' => 2023,
            'week' => 20,
            'category' => 'Fico Store',
            'content' => '<b>Este</b> es el contenido',
            'user_id' => $user_2->id,
            'type' => 'coach',
        ]);
    }

    /** @test */
    public function get_coaching(): void
    {
        $this->withoutExceptionHandling();

        $user_1 = User::factory()->withRole(Roles::ADMIN)->create([
            'company_id' => $this->user->company_id,
        ]);
        $user_2 = User::factory()->withRole(Roles::ADMIN)->create([
            'company_id' => $this->user->company_id,
        ]);
        $user_3 = User::factory()->withRole(Roles::ADMIN)->create([
            'company_id' => $this->user->company_id,
        ]);

        $performance_1 = Performance::factory()->create([
            'driver_amazon_id' => $user_1->driver_amazon_id,
            'week' => 29,
            'year' => 2023,
        ]);
        $performance_1v = Performance::factory()->create([
            'driver_amazon_id' => $user_1->driver_amazon_id,
            'week' => 30,
            'year' => 2023,
        ]);
        $performance_2 = Performance::factory()->create([
            'driver_amazon_id' => $user_2->driver_amazon_id,
            'week' => 30,
            'year' => 2023,
        ]);
        $performance_3 = Performance::factory()->create([
            'driver_amazon_id' => $user_3->driver_amazon_id,
            'week' => 31,
            'year' => 2023,
        ]);
        $this->get(action([CoachingController::class, 'get_coaching']))
            ->assertOk()
            ->assertExactJson([
                [
                    'id' => $this->user->id,
                    'name' => $this->user->firstname.' '.$this->user->lastname,
                    'driver_amazon_id' => $this->user->driver_amazon_id,
                    'performances' => [
                        [
                            'id' => null,
                            'overall_tier' => null,
                            'fico_score' => null,
                            'seatbelt_off_rate' => null,
                            'speeding_event_ratio' => null,
                            'distraction_rate' => null,
                            'following_distance_rate' => null,
                            'signal_violations_rate' => null,
                            'cdf' => null,
                            'dcr' => null,
                            'pod' => null,
                            'cc' => null,
                            'cc_o' => null,
                            'ced' => null,
                            'swc_ad' => null,
                            'dsb_dnr' => null,
                            'week' => 26,
                            'year' => 2023,
                        ],
                        [
                            'id' => null,
                            'overall_tier' => null,
                            'fico_score' => null,
                            'seatbelt_off_rate' => null,
                            'speeding_event_ratio' => null,
                            'distraction_rate' => null,
                            'following_distance_rate' => null,
                            'signal_violations_rate' => null,
                            'cdf' => null,
                            'dcr' => null,
                            'pod' => null,
                            'cc' => null,
                            'cc_o' => null,
                            'ced' => null,
                            'swc_ad' => null,
                            'dsb_dnr' => null,
                            'week' => 27,
                            'year' => 2023,
                        ],
                        [
                            'id' => null,
                            'overall_tier' => null,
                            'fico_score' => null,
                            'seatbelt_off_rate' => null,
                            'speeding_event_ratio' => null,
                            'distraction_rate' => null,
                            'following_distance_rate' => null,
                            'signal_violations_rate' => null,
                            'cdf' => null,
                            'dcr' => null,
                            'pod' => null,
                            'cc' => null,
                            'cc_o' => null,
                            'ced' => null,
                            'swc_ad' => null,
                            'dsb_dnr' => null,
                            'week' => 28,
                            'year' => 2023,
                        ],
                        [
                            'id' => null,
                            'overall_tier' => null,
                            'fico_score' => null,
                            'seatbelt_off_rate' => null,
                            'speeding_event_ratio' => null,
                            'distraction_rate' => null,
                            'following_distance_rate' => null,
                            'signal_violations_rate' => null,
                            'cdf' => null,
                            'dcr' => null,
                            'pod' => null,
                            'cc' => null,
                            'cc_o' => null,
                            'ced' => null,
                            'swc_ad' => null,
                            'dsb_dnr' => null,
                            'week' => 29,
                            'year' => 2023,
                        ],
                        [
                            'id' => null,
                            'overall_tier' => null,
                            'fico_score' => null,
                            'seatbelt_off_rate' => null,
                            'speeding_event_ratio' => null,
                            'distraction_rate' => null,
                            'following_distance_rate' => null,
                            'signal_violations_rate' => null,
                            'cdf' => null,
                            'dcr' => null,
                            'pod' => null,
                            'cc' => null,
                            'cc_o' => null,
                            'ced' => null,
                            'swc_ad' => null,
                            'dsb_dnr' => null,
                            'week' => 30,
                            'year' => 2023,
                        ],
                        [
                            'id' => null,
                            'overall_tier' => null,
                            'fico_score' => null,
                            'seatbelt_off_rate' => null,
                            'speeding_event_ratio' => null,
                            'distraction_rate' => null,
                            'following_distance_rate' => null,
                            'signal_violations_rate' => null,
                            'cdf' => null,
                            'dcr' => null,
                            'pod' => null,
                            'cc' => null,
                            'cc_o' => null,
                            'ced' => null,
                            'swc_ad' => null,
                            'dsb_dnr' => null,
                            'week' => 31,
                            'year' => 2023,
                        ],
                    ],
                ],
                [
                    'id' => $user_1->id,
                    'name' => $user_1->firstname.' '.$user_1->lastname,
                    'driver_amazon_id' => $user_1->driver_amazon_id,
                    'performances' => [
                        [
                            'id' => null,
                            'overall_tier' => null,
                            'fico_score' => null,
                            'seatbelt_off_rate' => null,
                            'speeding_event_ratio' => null,
                            'distraction_rate' => null,
                            'following_distance_rate' => null,
                            'signal_violations_rate' => null,
                            'cdf' => null,
                            'dcr' => null,
                            'pod' => null,
                            'cc' => null,
                            'cc_o' => null,
                            'ced' => null,
                            'swc_ad' => null,
                            'dsb_dnr' => null,
                            'week' => 26,
                            'year' => 2023,
                        ],
                        [
                            'id' => null,
                            'overall_tier' => null,
                            'fico_score' => null,
                            'seatbelt_off_rate' => null,
                            'speeding_event_ratio' => null,
                            'distraction_rate' => null,
                            'following_distance_rate' => null,
                            'signal_violations_rate' => null,
                            'cdf' => null,
                            'dcr' => null,
                            'pod' => null,
                            'cc' => null,
                            'cc_o' => null,
                            'ced' => null,
                            'swc_ad' => null,
                            'dsb_dnr' => null,
                            'week' => 27,
                            'year' => 2023,
                        ],
                        [
                            'id' => null,
                            'overall_tier' => null,
                            'fico_score' => null,
                            'seatbelt_off_rate' => null,
                            'speeding_event_ratio' => null,
                            'distraction_rate' => null,
                            'following_distance_rate' => null,
                            'signal_violations_rate' => null,
                            'cdf' => null,
                            'dcr' => null,
                            'pod' => null,
                            'cc' => null,
                            'cc_o' => null,
                            'ced' => null,
                            'swc_ad' => null,
                            'dsb_dnr' => null,
                            'week' => 28,
                            'year' => 2023,
                        ],
                        [
                            'id' => $performance_1->id,
                            'overall_tier' => "$performance_1->overall_tier",
                            'fico_score' => "$performance_1->fico_score",
                            'seatbelt_off_rate' => "$performance_1->seatbelt_off_rate",
                            'speeding_event_ratio' => "$performance_1->speeding_event_ratio",
                            'distraction_rate' => "$performance_1->distraction_rate",
                            'following_distance_rate' => "$performance_1->following_distance_rate",
                            'signal_violations_rate' => "$performance_1->signal_violations_rate",
                            'cdf' => "$performance_1->cdf",
                            'dcr' => "$performance_1->dcr",
                            'pod' => "$performance_1->swc_pod",
                            'cc' => "$performance_1->swc_cc",
                            'cc_o' => "$performance_1->cc",
                            'ced' => "$performance_1->ced",
                            'swc_ad' => "$performance_1->swc_ad",
                            'dsb_dnr' => "$performance_1->dsb_dnr",
                            'week' => 29,
                            'year' => 2023,
                        ],
                        [
                            'id' => $performance_1v->id,
                            'overall_tier' => "$performance_1v->overall_tier",
                            'fico_score' => "$performance_1v->fico_score",
                            'seatbelt_off_rate' => "$performance_1v->seatbelt_off_rate",
                            'speeding_event_ratio' => "$performance_1v->speeding_event_ratio",
                            'distraction_rate' => "$performance_1v->distraction_rate",
                            'following_distance_rate' => "$performance_1v->following_distance_rate",
                            'signal_violations_rate' => "$performance_1v->signal_violations_rate",
                            'cdf' => "$performance_1v->cdf",
                            'dcr' => "$performance_1v->dcr",
                            'pod' => "$performance_1v->swc_pod",
                            'cc' => "$performance_1v->swc_cc",
                            'cc_o' => "$performance_1v->cc",
                            'ced' => "$performance_1v->ced",
                            'swc_ad' => "$performance_1v->swc_ad",
                            'dsb_dnr' => "$performance_1v->dsb_dnr",
                            'week' => 30,
                            'year' => 2023,
                        ],

                        [
                            'id' => null,
                            'overall_tier' => null,
                            'fico_score' => null,
                            'seatbelt_off_rate' => null,
                            'speeding_event_ratio' => null,
                            'distraction_rate' => null,
                            'following_distance_rate' => null,
                            'signal_violations_rate' => null,
                            'cdf' => null,
                            'dcr' => null,
                            'pod' => null,
                            'cc' => null,
                            'cc_o' => null,
                            'ced' => null,
                            'swc_ad' => null,
                            'dsb_dnr' => null,
                            'week' => 31,
                            'year' => 2023,
                        ],
                    ],
                ],
                [
                    'id' => $user_2->id,
                    'name' => $user_2->firstname.' '.$user_2->lastname,
                    'driver_amazon_id' => $user_2->driver_amazon_id,
                    'performances' => [
                        [
                            'id' => null,
                            'overall_tier' => null,
                            'fico_score' => null,
                            'seatbelt_off_rate' => null,
                            'speeding_event_ratio' => null,
                            'distraction_rate' => null,
                            'following_distance_rate' => null,
                            'signal_violations_rate' => null,
                            'cdf' => null,
                            'dcr' => null,
                            'pod' => null,
                            'cc' => null,
                            'cc_o' => null,
                            'ced' => null,
                            'swc_ad' => null,
                            'dsb_dnr' => null,
                            'week' => 26,
                            'year' => 2023,
                        ],
                        [
                            'id' => null,
                            'overall_tier' => null,
                            'fico_score' => null,
                            'seatbelt_off_rate' => null,
                            'speeding_event_ratio' => null,
                            'distraction_rate' => null,
                            'following_distance_rate' => null,
                            'signal_violations_rate' => null,
                            'cdf' => null,
                            'dcr' => null,
                            'pod' => null,
                            'cc' => null,
                            'cc_o' => null,
                            'ced' => null,
                            'swc_ad' => null,
                            'dsb_dnr' => null,
                            'week' => 27,
                            'year' => 2023,
                        ],
                        [
                            'id' => null,
                            'overall_tier' => null,
                            'fico_score' => null,
                            'seatbelt_off_rate' => null,
                            'speeding_event_ratio' => null,
                            'distraction_rate' => null,
                            'following_distance_rate' => null,
                            'signal_violations_rate' => null,
                            'cdf' => null,
                            'dcr' => null,
                            'pod' => null,
                            'cc' => null,
                            'cc_o' => null,
                            'ced' => null,
                            'swc_ad' => null,
                            'dsb_dnr' => null,
                            'week' => 28,
                            'year' => 2023,
                        ],
                        [
                            'id' => null,
                            'overall_tier' => null,
                            'fico_score' => null,
                            'seatbelt_off_rate' => null,
                            'speeding_event_ratio' => null,
                            'distraction_rate' => null,
                            'following_distance_rate' => null,
                            'signal_violations_rate' => null,
                            'cdf' => null,
                            'dcr' => null,
                            'pod' => null,
                            'cc' => null,
                            'cc_o' => null,
                            'ced' => null,
                            'swc_ad' => null,
                            'dsb_dnr' => null,
                            'week' => 29,
                            'year' => 2023,
                        ],
                        [
                            'id' => $performance_2->id,
                            'overall_tier' => "$performance_2->overall_tier",
                            'fico_score' => "$performance_2->fico_score",
                            'seatbelt_off_rate' => "$performance_2->seatbelt_off_rate",
                            'speeding_event_ratio' => "$performance_2->speeding_event_ratio",
                            'distraction_rate' => "$performance_2->distraction_rate",
                            'following_distance_rate' => "$performance_2->following_distance_rate",
                            'signal_violations_rate' => "$performance_2->signal_violations_rate",
                            'cdf' => "$performance_2->cdf",
                            'dcr' => "$performance_2->dcr",
                            'pod' => "$performance_2->swc_pod",
                            'cc' => "$performance_2->swc_cc",
                            'cc_o' => "$performance_2->cc",
                            'ced' => "$performance_2->ced",
                            'swc_ad' => "$performance_2->swc_ad",
                            'dsb_dnr' => "$performance_2->dsb_dnr",
                            'week' => 30,
                            'year' => 2023,
                        ],
                        [
                            'id' => null,
                            'overall_tier' => null,
                            'fico_score' => null,
                            'seatbelt_off_rate' => null,
                            'speeding_event_ratio' => null,
                            'distraction_rate' => null,
                            'following_distance_rate' => null,
                            'signal_violations_rate' => null,
                            'cdf' => null,
                            'dcr' => null,
                            'pod' => null,
                            'cc' => null,
                            'cc_o' => null,
                            'ced' => null,
                            'swc_ad' => null,
                            'dsb_dnr' => null,
                            'week' => 31,
                            'year' => 2023,
                        ],
                    ],
                ],
                [
                    'id' => $user_3->id,
                    'name' => $user_3->firstname.' '.$user_3->lastname,
                    'driver_amazon_id' => $user_3->driver_amazon_id,
                    'performances' => [
                        [
                            'id' => null,
                            'overall_tier' => null,
                            'fico_score' => null,
                            'seatbelt_off_rate' => null,
                            'speeding_event_ratio' => null,
                            'distraction_rate' => null,
                            'following_distance_rate' => null,
                            'signal_violations_rate' => null,
                            'cdf' => null,
                            'dcr' => null,
                            'pod' => null,
                            'cc' => null,
                            'cc_o' => null,
                            'ced' => null,
                            'swc_ad' => null,
                            'dsb_dnr' => null,
                            'week' => 26,
                            'year' => 2023,
                        ],
                        [
                            'id' => null,
                            'overall_tier' => null,
                            'fico_score' => null,
                            'seatbelt_off_rate' => null,
                            'speeding_event_ratio' => null,
                            'distraction_rate' => null,
                            'following_distance_rate' => null,
                            'signal_violations_rate' => null,
                            'cdf' => null,
                            'dcr' => null,
                            'pod' => null,
                            'cc' => null,
                            'cc_o' => null,
                            'ced' => null,
                            'swc_ad' => null,
                            'dsb_dnr' => null,
                            'week' => 27,
                            'year' => 2023,
                        ],
                        [
                            'id' => null,
                            'overall_tier' => null,
                            'fico_score' => null,
                            'seatbelt_off_rate' => null,
                            'speeding_event_ratio' => null,
                            'distraction_rate' => null,
                            'following_distance_rate' => null,
                            'signal_violations_rate' => null,
                            'cdf' => null,
                            'dcr' => null,
                            'pod' => null,
                            'cc' => null,
                            'cc_o' => null,
                            'ced' => null,
                            'swc_ad' => null,
                            'dsb_dnr' => null,
                            'week' => 28,
                            'year' => 2023,
                        ],
                        [
                            'id' => null,
                            'overall_tier' => null,
                            'fico_score' => null,
                            'seatbelt_off_rate' => null,
                            'speeding_event_ratio' => null,
                            'distraction_rate' => null,
                            'following_distance_rate' => null,
                            'signal_violations_rate' => null,
                            'cdf' => null,
                            'dcr' => null,
                            'pod' => null,
                            'cc' => null,
                            'cc_o' => null,
                            'ced' => null,
                            'swc_ad' => null,
                            'dsb_dnr' => null,
                            'week' => 29,
                            'year' => 2023,
                        ],
                        [
                            'id' => null,
                            'overall_tier' => null,
                            'fico_score' => null,
                            'seatbelt_off_rate' => null,
                            'speeding_event_ratio' => null,
                            'distraction_rate' => null,
                            'following_distance_rate' => null,
                            'signal_violations_rate' => null,
                            'cdf' => null,
                            'dcr' => null,
                            'pod' => null,
                            'cc' => null,
                            'cc_o' => null,
                            'ced' => null,
                            'swc_ad' => null,
                            'dsb_dnr' => null,
                            'week' => 30,
                            'year' => 2023,
                        ],
                        [
                            'id' => $performance_3->id,
                            'overall_tier' => "$performance_3->overall_tier",
                            'fico_score' => "$performance_3->fico_score",
                            'seatbelt_off_rate' => "$performance_3->seatbelt_off_rate",
                            'speeding_event_ratio' => "$performance_3->speeding_event_ratio",
                            'distraction_rate' => "$performance_3->distraction_rate",
                            'following_distance_rate' => "$performance_3->following_distance_rate",
                            'signal_violations_rate' => "$performance_3->signal_violations_rate",
                            'cdf' => "$performance_3->cdf",
                            'dcr' => "$performance_3->dcr",
                            'pod' => "$performance_3->swc_pod",
                            'cc' => "$performance_3->swc_cc",
                            'cc_o' => "$performance_3->cc",
                            'ced' => "$performance_3->ced",
                            'swc_ad' => "$performance_3->swc_ad",
                            'dsb_dnr' => "$performance_3->dsb_dnr",
                            'week' => 31,
                            'year' => 2023,
                        ],
                    ],
                ],
            ]);
    }
}
