-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg6s94AskRlFSFMh6q
atd2ZCCyLXWqbY9sNAiS/zfWa6ugCgYIKoZIzj0DAQehRANCAAS1ki+BvwHRgYFR
u/XG0XobUROmYEdyVImQWTmWo+KLuaVTuim12urSzqZ6NK9TKhY52mYVnWWfaQQv
fwFdSaRq
-----END PRIVATE KEY-----